### ISSUE TITLE
Error in test run

### ISSUE THREAD

**Issue by sadiogo** [ChengfeiYan/DRN-1D2D#1]
Hello!

I've installed everything like described in README file and when I ran the test I got the following traceback:
```
Final output files: TMP_DISOPRED_3402_2022_01_27_08_10_56_temp.diso TMP_DISOPRED_3402_2022_01_27_08_10_56_temp.horiz_d
Cleaning up ....
SS3 FILE /home/sadiogo/DRN-1D2D/bin/TGT_Package/tmp///temp.ss2 length not equal [164!=0]
SS8 FILE /home/sadiogo/DRN-1D2D/bin/TGT_Package/tmp///temp.ss8 length not equal [164!=0]
 ERROR: 3 rows; 0 cols.
Cannot open accfile /home/sadiogo/DRN-1D2D/bin/TGT_Package/tmp//temp.acc
cp: cannot stat './bin/TGT_Package/temp.tgt': No such file or directory
ERROR tgt
Traceback (most recent call last):
  File "./scripts/predictor.py", line 102, in <module>
    feature = cat_feature(save_path,name,1700)
  File "/home/sadiogo/DRN-1D2D/scripts/read_feature.py", line 73, in cat_feature
    PSSM,PSFM = read_pssm(pssm_file)
  File "/home/sadiogo/DRN-1D2D/scripts/read_feature.py", line 15, in read_pssm
    fr = open(pssm_file,'rb+')
FileNotFoundError: [Errno 2] No such file or directory: '/home/sadiogo/DRN-1D2D/example/test/test_hhm.pkl'
```

Can you help me solve this problem?

**Comment by ChengfeiYan** [comment]
Hi Sadiogo, 
Sorry for the late reply, and hopefully the problem has been solved!
It seems that the predicted secondary structure file (SS3)  has not been successfully generated. The secondary structure prediction is implemented by a third party package TGT_Package. You may contact https://github.com/realbigws/TGT_Package for additional help.
If you need a quick reply, please contact me through email (chengfeiyan@hust.edu.cn).
Chengfei Yan
